//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Daenet
{
    using System;
    using System.Collections.Generic;
    
    public partial class SasDeviceDetail
    {
        public string DeviceName { get; set; }
        public string DeviceKey { get; set; }
        public string Ip { get; set; }
        public string Owner { get; set; }
        public string Location { get; set; }
        public int DeviceId { get; set; }
        public System.DateTime KeyValidity { get; set; }
    }
}
